apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: set-commit-status-el
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: set-commit-status
      interceptors:
        - cel:
            # limit to github and gitlab push/merge for now
            filter: >-
              (header.match('X-GitHub-Event', 'pull_request') && body.action in ['opened', 'reopened']) ||
              header.match('X-GitHub-Event', 'push') ||
              (header.match('X-Gitlab-Event', 'Merge Request Hook') && (body.changes == {} || body.object_attributes.action == "reopen")) ||
              header.match('X-Gitlab-Event', 'Push Hook')
            overlays:
              - key: marshalled-body
                expression: body.marshalJSON()
              # used for checking header
              # - key: marshalled-header
              #   expression: header.marshalJSON()
      bindings:
        - ref: set-commit-status-tb
      template:
        ref: set-commit-status-tt